# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-02 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20160702_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='divx',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='divy',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
