# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-02 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20160702_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='divx',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='divy',
            field=models.IntegerField(null=True),
        ),
    ]
