# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20160913_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='pieceAA',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceAAstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceAB',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceABstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceAC',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceACstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceAD',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceADstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceAE',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceAEstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceAF',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceAFstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceAG',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceAGstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceAH',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceAHstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceAI',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceAIstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceAJ',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceAJstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceAK',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceAKstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceAL',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceALstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceAM',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceAMstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceAN',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceANstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceAO',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceAOstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceAP',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceAPstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceAQ',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceAQstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceAR',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceARstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceAS',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceASstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceAT',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceATstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceBA',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceBAstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceBB',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceBBstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceBC',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceBCstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceBD',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceBDstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceBE',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceBEstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceBF',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceBFstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceBG',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceBGstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceBH',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceBHstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceBI',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceBIstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceBJ',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceBJstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceBK',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceBKstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceBL',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceBLstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceBM',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceBMstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceBN',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceBNstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceBO',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceBOstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceBP',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceBPstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceBQ',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceBQstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceBR',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceBRstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceBS',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceBSstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceBT',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceBTstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceCA',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceCAstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceCB',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceCBstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceCC',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceCCstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceCD',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceCDstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceCE',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceCEstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceCF',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceCFstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceCG',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceCGstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceCH',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceCHstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceCI',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceCIstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceCJ',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceCJstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceCK',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceCKstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceCL',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceCLstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceCM',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceCMstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceCN',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceCNstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceCO',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceCOstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceCP',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceCPstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceCQ',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceCQstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceCR',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceCRstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceCS',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceCSstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceCT',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceCTstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceDA',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceDAstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceDB',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceDBstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceDC',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceDCstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceDD',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceDDstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceDE',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceDEstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceDF',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceDFstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceDG',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceDGstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceDH',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceDHstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceDI',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceDIstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceDJ',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceDJstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceDK',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceDKstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceDL',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceDLstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceDM',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceDMstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceDN',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceDNstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceDO',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceDOstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceDP',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceDPstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceDQ',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceDQstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceDR',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceDRstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceDS',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceDSstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceDT',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceDTstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceEA',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceEAstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceEB',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceEBstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceEC',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceECstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceED',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceEDstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceEE',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceEEstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceEF',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceEFstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceEG',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceEGstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceEH',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceEHstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceEI',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceEIstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceEJ',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceEJstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceEK',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceEKstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceEL',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceELstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceEM',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceEMstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceEN',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceENstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceEO',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceEOstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceEP',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceEPstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceEQ',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceEQstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceER',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceERstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceES',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceESstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceET',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceETstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceFA',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceFAstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceFB',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceFBstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceFC',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceFCstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceFD',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceFDstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceFE',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceFEstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceFF',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceFFstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceFG',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceFGstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceFH',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceFHstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceFI',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceFIstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceFJ',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceFJstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceFK',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceFKstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceFL',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceFLstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceFM',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceFMstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceFN',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceFNstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceFO',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceFOstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceFP',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceFPstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceFQ',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceFQstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceFR',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceFRstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceFS',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceFSstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceFT',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceFTstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceGA',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceGAstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceGB',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceGBstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceGC',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceGCstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceGD',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceGDstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceGE',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceGEstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceGF',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceGFstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceGG',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceGGstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceGH',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceGHstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceGI',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceGIstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceGJ',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceGJstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceGK',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceGKstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceGL',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceGLstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceGM',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceGMstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceGN',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceGNstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceGO',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceGOstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceGP',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceGPstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceGQ',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceGQstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceGR',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceGRstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceGS',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceGSstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceGT',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceGTstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceHA',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceHAstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceHB',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceHBstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceHC',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceHCstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceHD',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceHDstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceHE',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceHEstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceHF',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceHFstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceHG',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceHGstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceHH',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceHHstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceHI',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceHIstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceHJ',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceHJstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceHK',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceHKstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceHL',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceHLstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceHM',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceHMstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceHN',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceHNstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceHO',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceHOstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceHP',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceHPstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceHQ',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceHQstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceHR',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceHRstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceHS',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceHSstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceHT',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceHTstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceIA',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceIAstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceIB',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceIBstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceIC',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceICstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceID',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceIDstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceIE',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceIEstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceIF',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceIFstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceIG',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceIGstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceIH',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceIHstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceII',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceIIstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceIJ',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceIJstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceIK',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceIKstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceIL',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceILstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceIM',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceIMstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceIN',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceINstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceIO',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceIOstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceIP',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceIPstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceIQ',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceIQstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceIR',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceIRstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceIS',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceISstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceIT',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceITstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceJA',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceJAstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceJB',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceJBstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceJC',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceJCstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceJD',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceJDstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceJE',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceJEstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceJF',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceJFstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceJG',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceJGstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceJH',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceJHstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceJI',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceJIstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceJJ',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceJJstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceJK',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceJKstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceJL',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceJLstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceJM',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceJMstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceJN',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceJNstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceJO',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceJOstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceJP',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceJPstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceJQ',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceJQstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceJR',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceJRstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceJS',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceJSstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceJT',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceJTstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceKA',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceKAstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceKB',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceKBstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceKC',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceKCstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceKD',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceKDstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceKE',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceKEstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceKF',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceKFstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceKG',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceKGstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceKH',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceKHstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceKI',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceKIstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceKJ',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceKJstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceKK',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceKKstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceKL',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceKLstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceKM',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceKMstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceKN',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceKNstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceKO',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceKOstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceKP',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceKPstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceKQ',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceKQstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceKR',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceKRstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceKS',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceKSstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceKT',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceKTstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceLA',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceLAstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceLB',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceLBstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceLC',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceLCstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceLD',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceLDstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceLE',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceLEstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceLF',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceLFstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceLG',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceLGstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceLH',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceLHstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceLI',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceLIstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceLJ',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceLJstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceLK',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceLKstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceLL',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceLLstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceLM',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceLMstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceLN',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceLNstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceLO',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceLOstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceLP',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceLPstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceLQ',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceLQstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceLR',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceLRstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceLS',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceLSstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceLT',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceLTstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceMA',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceMAstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceMB',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceMBstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceMC',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceMCstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceMD',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceMDstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceME',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceMEstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceMF',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceMFstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceMG',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceMGstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceMH',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceMHstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceMI',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceMIstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceMJ',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceMJstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceMK',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceMKstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceML',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceMLstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceMM',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceMMstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceMN',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceMNstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceMO',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceMOstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceMP',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceMPstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceMQ',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceMQstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceMR',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceMRstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceMS',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceMSstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceMT',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceMTstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceNA',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceNAstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceNB',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceNBstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceNC',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceNCstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceND',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceNDstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceNE',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceNEstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceNF',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceNFstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceNG',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceNGstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceNH',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceNHstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceNI',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceNIstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceNJ',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceNJstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceNK',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceNKstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceNL',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceNLstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceNM',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceNMstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceNN',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceNNstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceNO',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceNOstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceNP',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceNPstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceNQ',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceNQstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceNR',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceNRstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceNS',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceNSstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceNT',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceNTstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceOA',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceOAstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceOB',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceOBstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceOC',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceOCstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceOD',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceODstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceOE',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceOEstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceOF',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceOFstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceOG',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceOGstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceOH',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceOHstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceOI',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceOIstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceOJ',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceOJstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceOK',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceOKstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceOL',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceOLstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceOM',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceOMstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceON',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceONstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceOO',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceOOstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceOP',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceOPstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceOQ',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceOQstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceOR',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceORstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceOS',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceOSstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceOT',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceOTstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='piecePA',
        ),
        migrations.RemoveField(
            model_name='document',
            name='piecePAstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='piecePB',
        ),
        migrations.RemoveField(
            model_name='document',
            name='piecePBstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='piecePC',
        ),
        migrations.RemoveField(
            model_name='document',
            name='piecePCstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='piecePD',
        ),
        migrations.RemoveField(
            model_name='document',
            name='piecePDstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='piecePE',
        ),
        migrations.RemoveField(
            model_name='document',
            name='piecePEstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='piecePF',
        ),
        migrations.RemoveField(
            model_name='document',
            name='piecePFstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='piecePG',
        ),
        migrations.RemoveField(
            model_name='document',
            name='piecePGstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='piecePH',
        ),
        migrations.RemoveField(
            model_name='document',
            name='piecePHstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='piecePI',
        ),
        migrations.RemoveField(
            model_name='document',
            name='piecePIstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='piecePJ',
        ),
        migrations.RemoveField(
            model_name='document',
            name='piecePJstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='piecePK',
        ),
        migrations.RemoveField(
            model_name='document',
            name='piecePKstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='piecePL',
        ),
        migrations.RemoveField(
            model_name='document',
            name='piecePLstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='piecePM',
        ),
        migrations.RemoveField(
            model_name='document',
            name='piecePMstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='piecePN',
        ),
        migrations.RemoveField(
            model_name='document',
            name='piecePNstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='piecePO',
        ),
        migrations.RemoveField(
            model_name='document',
            name='piecePOstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='piecePP',
        ),
        migrations.RemoveField(
            model_name='document',
            name='piecePPstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='piecePQ',
        ),
        migrations.RemoveField(
            model_name='document',
            name='piecePQstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='piecePR',
        ),
        migrations.RemoveField(
            model_name='document',
            name='piecePRstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='piecePS',
        ),
        migrations.RemoveField(
            model_name='document',
            name='piecePSstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='piecePT',
        ),
        migrations.RemoveField(
            model_name='document',
            name='piecePTstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceQA',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceQAstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceQB',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceQBstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceQC',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceQCstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceQD',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceQDstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceQE',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceQEstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceQF',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceQFstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceQG',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceQGstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceQH',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceQHstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceQI',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceQIstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceQJ',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceQJstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceQK',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceQKstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceQL',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceQLstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceQM',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceQMstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceQN',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceQNstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceQO',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceQOstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceQP',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceQPstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceQQ',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceQQstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceQR',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceQRstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceQS',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceQSstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceQT',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceQTstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceRA',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceRAstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceRB',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceRBstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceRC',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceRCstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceRD',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceRDstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceRE',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceREstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceRF',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceRFstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceRG',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceRGstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceRH',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceRHstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceRI',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceRIstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceRJ',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceRJstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceRK',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceRKstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceRL',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceRLstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceRM',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceRMstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceRN',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceRNstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceRO',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceROstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceRP',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceRPstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceRQ',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceRQstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceRR',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceRRstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceRS',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceRSstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceRT',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceRTstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceSA',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceSAstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceSB',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceSBstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceSC',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceSCstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceSD',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceSDstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceSE',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceSEstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceSF',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceSFstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceSG',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceSGstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceSH',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceSHstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceSI',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceSIstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceSJ',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceSJstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceSK',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceSKstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceSL',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceSLstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceSM',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceSMstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceSN',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceSNstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceSO',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceSOstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceSP',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceSPstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceSQ',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceSQstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceSR',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceSRstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceSS',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceSSstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceST',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceSTstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceTA',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceTAstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceTB',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceTBstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceTC',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceTCstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceTD',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceTDstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceTE',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceTEstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceTF',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceTFstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceTG',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceTGstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceTH',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceTHstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceTI',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceTIstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceTJ',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceTJstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceTK',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceTKstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceTL',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceTLstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceTM',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceTMstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceTN',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceTNstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceTO',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceTOstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceTP',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceTPstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceTQ',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceTQstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceTR',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceTRstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceTS',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceTSstate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceTT',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pieceTTstate',
        ),
    ]
