# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_auto_20161014_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='mosaic',
            field=models.ImageField(default='null', upload_to='documents/%Y/%m/%d'),
        ),
    ]
