# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_auto_20161016_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='submit_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
