# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 14:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_auto_20161016_2056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='piece',
            old_name='submit_date',
            new_name='given_date',
        ),
    ]
