# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_auto_20161016_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='ip',
            field=models.CharField(default='null', max_length=30),
        ),
    ]
