# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_piece_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banned',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(default='null', max_length=30)),
                ('documentidentifier', models.CharField(default='null', max_length=8)),
            ],
        ),
    ]
