# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 04:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_banned'),
    ]

    operations = [
        migrations.AddField(
            model_name='banned',
            name='identifier',
            field=models.CharField(default='null', max_length=15),
        ),
    ]
