# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-28 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_banned_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='ip',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='piece',
            name='owner',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
