# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-13 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_auto_20161128_0911'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deletion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(default='null', max_length=15)),
                ('owner', models.CharField(max_length=30, null=True)),
                ('number_of_pieces', models.CharField(max_length=5, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('deletion_date', models.DateTimeField(blank=True, null=True)),
                ('pieces_given_report', models.CharField(max_length=10, null=True)),
                ('pieces_accepted_report', models.CharField(max_length=10, null=True)),
                ('pieces_submited_report', models.CharField(max_length=10, null=True)),
                ('pieces_unused_report', models.CharField(max_length=10, null=True)),
                ('time_of_life', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
