# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-13 06:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_deletion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deletion',
            old_name='pieces_accepted_report',
            new_name='pieces_accepted',
        ),
        migrations.RenameField(
            model_name='deletion',
            old_name='pieces_given_report',
            new_name='pieces_given',
        ),
        migrations.RenameField(
            model_name='deletion',
            old_name='pieces_submited_report',
            new_name='pieces_submited',
        ),
        migrations.RenameField(
            model_name='deletion',
            old_name='pieces_unused_report',
            new_name='pieces_unused',
        ),
    ]
